version: '3'
services:
  customers:
    container_name: customers
    image: customers:latest
    ports:
      - "8081:8081"
    networks:
      - spring-network

  rest-client:
    container_name: rest-client
    image: rest-client:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge